name: VyaaparNexus-env
values:
  - key: baseUrl
    value: 'http://localhost:5117'
  - key: api-key
    value: vyaaparnexus-demo-key-2026
  - key: testProductId
    value: a5620eea-4fff-4c4f-b0d9-b5eecbeda4bb
  - key: testCustomerId
    value: e0d0b000-0000-0000-0000-000000000005
